# Generated by Django 6.0.3 on 2026-05-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_exam_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
    ]
