# Generated by Django 6.0.3 on 2026-05-01 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exam_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('coding', 'Coding'), ('descriptive', 'Descriptive')], max_length=20)),
                ('option1', models.CharField(blank=True, max_length=200, null=True)),
                ('option2', models.CharField(blank=True, max_length=200, null=True)),
                ('option3', models.CharField(blank=True, max_length=200, null=True)),
                ('option4', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('marks', models.IntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
