# Generated by Django 6.0.3 on 2026-05-09 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_aptitude_score_result_obtained_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='result',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='result',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='university_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(help_text='Duration in Minutes'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
